version: 2.1
orbs:
  python: circleci/python@3.12.2

jobs:
  test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo 'building'

workflows:
  test_my_app:
    jobs:
      - build
      - test:
          requires:
            - build
