version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: echo 'running tests'
  build:
    machine:
      image: linux-cuda-12:default
      resource_class: gpu.nvidia.medium
    steps:
      - run: nvidia-smi

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
